import { Onest } from "next/font/google"
import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";

const onest = Onest({
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--onest",
  subsets: ["latin"],
  preload: true
})

export const metadata = {
  title: "Parth Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${onest.variable} font-Onest`}>
        <div className="flex flex-col w-full min-h-screen bg-black">
          {/* Header */}
          <Header />

          <div className="flex-1">
            {children}
          </div>

          {/* Footer */}
          <Footer />
        </div>
      </body>
    </html>
  );
}
