import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import localFont from "next/font/local";
import { Toaster } from "@/components/ui/sonner";

export const gilroy = localFont({
  src: [
    { path: "./fonts/Gilroy-Thin.woff2", weight: "100", style: "normal" },
    { path: "./fonts/Gilroy-Light.woff2", weight: "300", style: "normal" },
    { path: "./fonts/Gilroy-Regular.woff2", weight: "400", style: "normal" },
    { path: "./fonts/Gilroy-Medium.woff2", weight: "500", style: "normal" },
    { path: "./fonts/Gilroy-Bold.woff2", weight: "700", style: "normal" },
    { path: "./fonts/Gilroy-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--Gilroy",
});

export const gyahegi = localFont({
  src: [
    { path: "./fonts/Gyahegi.woff2", weight: "400", style: "normal" },
  ],
  variable: "--Gyahegi",
});

export const slatyFeather = localFont({
  src: [
    { path: "./fonts/Salty-Feathers.woff2", style: "normal" },
  ],
  variable: "--SaltyFeathers",
});

export const metadata = {
  title: "Parth Studio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${gilroy.variable} ${slatyFeather.variable} ${gyahegi.variable} font-Gilroy w-full`}>
        <Navbar />
        <div className="flex items-center justify-center w-full">
          <div className="w-full min-h-screen">
            {children}
          </div>
        </div>
        <Footer />
        <Toaster />
      </body>
    </html>
  );
}