import Navbar from '@/components/Navbar'
import './globals.css'
import Footer from '@/components/Footer'

export const metadata = {
  title: 'Parth Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-white h-screen flex flex-col">
        <Navbar />
        <div className="flex-1 overflow-y-auto">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
